notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
script:
- pip install codecov
- python setup.py sdist
- python setup.py test
- coverage run --source=flask_objectid_converter --branch setup.py test
- coverage report -m
- codecov
jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: Fischerfredl
        password:
          secure: Uxj4nfjC/dxjR0DybBE6xSHYnGPe0/nJCyTdEruVk6k6ASm4/4zGI/xQFgGbIZgHC4gyh8LKkjt/wKnSaGm9Lahu9ZF3G2ieBGzi8AhlBSWQXkFt78hCYx/RW4AH5+IrN31BTt2wjLY1ZOZRwbpCYgcUGLJb1pYj3m1yFVP2u6aKaS5e5mJCOQJZOT42gTdLFCyv6ApmCiZgV8Uz3xAiZNj+wInUBMgT7sSdxgBNV4w1PIyuy6L8ivpKqdmy3soSn8osbfnp16E2ys1DyMTE9e3P0NZ0hmZgVEqFjEhk5eRfmmfg6EUknGaP0bkK1ESq7DJWWw+g9fn3nBewX62a4ISHyLAS+XR0qlgZvg3532LmBXhTnkyX7VmKPAMMKe3WvRQF3psT7ZDql2UvwIDoW+m0sUmdpAk54vYde85uMQ5OAyTjuimMgfiRnyIM7CKT93gbc/q/iYmAChk0LsxMp1lkFyNQ+UNjzigZaElCqbkFqpO+g33AyrA+IPoBkp2Z5rzxTo0t8+acpYD8GQG6AHTao2v/AUK5eP/jeEwPNfrOm88y0FcwmOogdIfGU7p8tGcN2zoJw+qRDvE8bJ2LAR9s8NTYn+L1HUK3SvVBaQ0l1fzPet3GCZ2jWzgvPSiGkbdMM3sfItnw8h1OatXCMWOfr2Wm5ZmLSyKfDi+0e74=
        on:
          tags: true
